import "@/app/globals.css";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Acenda | Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="grid md:grid-cols-[1fr_0.8fr] grid-cols-1 h-screen overflow-y-scroll">
      {children}
    </main>
  );
}
