import "@/app/globals.css";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Acenda | Auth",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="grid grid-cols-[1fr_0.8fr] h-screen overflow-hidden">
      {children}
    </main>
  );
}
