import "@/app/globals.css";
import Footer from "@/components/ui/Footer";
import Header from "@/components/ui/Header";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Acenda | Main",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen px-12 min-w-full">
      <Header />
      {children}
      <Footer />
    </main>
  );
}
