import "@/app/globals.css";
import ScrollToTop from "@/components/ScrollToTop";
import ChatWidget from "@/components/ui/ChatWidget";
import Footer from "@/components/ui/Footer";
import Header from "@/components/ui/Header";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Acenda | Main",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ScrollToTop />
      <Header />
      <main className="min-h-screen xl:px-12 md:px-6 px-3 ">
        {children}
        <ChatWidget />
      </main>
      <Footer />
    </>
  );
}
