import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
// Import ShopeeDisplay font family
const shopeeDisplay = localFont({
  src: [
    {
      path: "../font/ShopeeDisplay-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-shopee",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${shopeeDisplay.variable}`}>
      <body className="antialiased min-h-screen font-sans">{children}</body>
    </html>
  );
}
