import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
// Import ShopeeDisplay font family
const shopeeDisplay = localFont({
  src: [
    {
      path: "../font/ShopeeDisplay-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/ShopeeDisplay-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-shopee",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${shopeeDisplay.variable}`}>
      <Toaster
        position="top-center"
        gutter={12}
        containerStyle={{ margin: "4px" }}
        toastOptions={{
          success: { duration: 3000 },
          error: { duration: 4000 },
          style: {
            fontSize: "14px",
            fontWeight: "500",
            color: "#202C46",
            textWrap: "nowrap",
            maxWidth: "400px",
            padding: "14px 20px",
          },
        }}
      />
      <body className="antialiased min-h-screen font-sans">{children}</body>
    </html>
  );
}
